# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa35f6f75c8d786209b0402339d9c76f42cab91fbfaa117a23451eed700844eee23c713d445cd869f6782071a3f08b59f406c8486a140ca7be40d0e88844bbf5

test:
  secret_key_base: c9f5ef5aeec1f42161c9e0e2ffe37b047af80c0d333d797f45ef9dd1875a136190fc5a3b8d98c099751429d26f3923b4d601f370c39ab743c28321156aebd3b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
